name: More and More
description: Hello World!
meta_description: "Hello World!"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
url: 'http://webjjel.github.io'
google_analytics: 'UA-75513441-1'
gems: [jekyll-paginate]
permalink: pretty

timezone: Asia/Seoul


host: 0.0.0.0



theme: jekyll-theme-cayman