name: More and More
description: Hello World!
meta_description: "Hello World!"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: ""
url: 'http://local.webjjel.github.io:4000'
#google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
permalink: pretty


host: 0.0.0.0


